-- =====================================================================
-- Toronto Green Space Tier Classification
-- ArcGIS Pro Select By Attributes (file geodatabase SQL)
--
-- Each query runs independently against the UNMODIFIED source layer
-- (City of Toronto Green Spaces, 3,379 polygons).
-- Priority order: Hard exclusions > Tier 1 > Tier 2 > Tier 3 > Excluded catch-all
-- Each query excludes every higher-priority category with AND NOT.
-- Note: LIKE is case-sensitive in a file geodatabase; source names are uppercase.
--
-- Final counts: Tier 1 = 1,929 | Tier 2 = 233 | Tier 3 = 258 | Excluded = 959
-- =====================================================================


-- ---------------------------------------------------------------------
-- TIER 1: Formal and manicured parks
-- ---------------------------------------------------------------------
(AREA_CL6 = 'Park' Or AREA_CL6 = 'Civic Centre Square' Or AREA_CL6 = 'Open Green Space' Or AREA_NA9 LIKE '%PARK%' Or AREA_NA9 LIKE '%PLAYGROUND%' Or AREA_NA9 LIKE '%ATHLETIC%' Or AREA_NA9 LIKE '%RECREATION%' Or AREA_NA9 LIKE '%SPORT%' Or AREA_NA9 LIKE '%CIVIC CENTRE%' Or AREA_NA9 LIKE '%CIVIC CENTER%')
AND NOT
(AREA_CL6 = 'Cemetery' Or AREA_CL6 = 'Cul de Sac' Or AREA_CL6 = 'Golf Course' Or AREA_CL6 = 'OTHER_CEMETERY' Or AREA_CL6 = 'OTHER_GOLFCOURSE' Or AREA_CL6 = 'Traffic Island' Or AREA_NA9 LIKE '%CITY WIDE OPEN SPACE%' Or AREA_NA9 LIKE '%PUBLIC ACCESS PROPERTY%' Or AREA_NA9 LIKE '%ZOO%' Or AREA_NA9 LIKE '%OLD FORT YORK%' Or AREA_NA9 LIKE '%EXHIBITION PLACE%' Or AREA_NA9 LIKE '%MUSEUM%' Or AREA_NA9 LIKE '%SCHOOL%' Or AREA_NA9 LIKE '%GOLF%' Or AREA_NA9 LIKE '%CEMETERY%' Or AREA_NA9 LIKE '%GRAVE%' Or AREA_NA9 LIKE '%MEDIAN%' Or AREA_NA9 LIKE '%TRAFFIC%' Or AREA_NA9 LIKE '%ROAD%' Or AREA_NA9 LIKE '%HIGHWAY%' Or AREA_NA9 LIKE '%EXPRESSWAY%' Or AREA_NA9 LIKE '%FREEWAY%' Or AREA_NA9 LIKE '%PARKING%' Or AREA_NA9 LIKE '%DRIVEWAY%' Or AREA_NA9 LIKE '%RAIL%' Or AREA_NA9 LIKE '%BUILDING%' Or AREA_NA9 LIKE '%STATION%' Or AREA_NA9 LIKE '%HOSPITAL%' Or AREA_NA9 LIKE '%INSTITUTION%' Or AREA_NA9 LIKE '%CAMPUS%' Or AREA_NA9 LIKE '%FACILITY%' Or AREA_NA9 LIKE '%OFFICE%' Or AREA_NA9 LIKE '%INDUSTRIAL%' Or AREA_NA9 LIKE '%LANDFILL%' Or AREA_NA9 LIKE '%TREATMENT%' Or AREA_NA9 LIKE '%RESTRICTED%' Or AREA_NA9 LIKE '%PROPOSED%' Or AREA_NA9 LIKE '%RESIDENTIAL%' Or AREA_NA9 LIKE '%GATED%' Or AREA_NA9 LIKE '%MEMBER%')


-- ---------------------------------------------------------------------
-- TIER 2: Natural heritage, natural and trail spaces
-- Includes named exceptions for keyword false positives (e.g. %WOOD% in building names)
-- ---------------------------------------------------------------------
(AREA_NA9 LIKE '%RAVINE%' Or AREA_NA9 LIKE '%CREEK%' Or AREA_NA9 LIKE '%RIVER%' Or AREA_NA9 LIKE '%WATERCOURSE%' Or AREA_NA9 LIKE '%WOOD%' Or AREA_NA9 LIKE '%FOREST%' Or AREA_NA9 LIKE '%CONSERVATION%' Or AREA_NA9 LIKE '%NATURE%' Or AREA_NA9 LIKE '%NATURAL%' Or AREA_NA9 LIKE '%HERITAGE%' Or AREA_NA9 LIKE '%WETLAND%' Or AREA_NA9 LIKE '%MARSH%' Or AREA_NA9 LIKE '%MEADOW%' Or AREA_NA9 LIKE '%VALLEY%' Or AREA_NA9 LIKE '%ESCARPMENT%' Or AREA_NA9 LIKE '%BLUFF%' Or AREA_NA9 LIKE '%BEACH%' Or AREA_NA9 LIKE '%SYSTEM%' Or AREA_NA9 LIKE '%WATERSHED%' Or AREA_NA9 LIKE '%GREENBELT%' Or AREA_NA9 LIKE '%TRAIL%' Or AREA_NA9 LIKE '%WATERFRONT%' Or AREA_NA9 LIKE '%LAKEFRONT%' Or AREA_NA9 LIKE '%HARBOURFRONT%' Or AREA_NA9 LIKE '%BOARDWALK%' Or AREA_NA9 LIKE '%SHORELINE%' Or AREA_NA9 LIKE '%ISLAND%' Or AREA_NA9 LIKE '%HABITAT%' Or AREA_NA9 LIKE '%SANCTUARY%' Or AREA_NA9 LIKE '%ECOLOGICAL%' Or AREA_NA9 LIKE '%PRESERVE%' Or AREA_NA9 LIKE '%POND%' Or AREA_NA9 LIKE '%ARBORETUM%')
AND NOT
(AREA_NA9 LIKE '%HARWOOD HALL%' Or AREA_NA9 LIKE '%CRESTWOOD COLLEGE%' Or AREA_NA9 LIKE '%YORKWOODS LIBRARY%' Or AREA_NA9 LIKE '%NORTHWOOD COMMUNITY CENTRE%' Or AREA_NA9 LIKE '%CLIFFWOOD MANOR%' Or AREA_NA9 LIKE '%PIONEER%')
AND NOT
(AREA_CL6 = 'Park' Or AREA_CL6 = 'Civic Centre Square' Or AREA_CL6 = 'Open Green Space' Or AREA_NA9 LIKE '%PARK%' Or AREA_NA9 LIKE '%PLAYGROUND%' Or AREA_NA9 LIKE '%ATHLETIC%' Or AREA_NA9 LIKE '%RECREATION%' Or AREA_NA9 LIKE '%SPORT%' Or AREA_NA9 LIKE '%CIVIC CENTRE%' Or AREA_NA9 LIKE '%CIVIC CENTER%')
AND NOT
(AREA_CL6 = 'Cemetery' Or AREA_CL6 = 'Cul de Sac' Or AREA_CL6 = 'Golf Course' Or AREA_CL6 = 'OTHER_CEMETERY' Or AREA_CL6 = 'OTHER_GOLFCOURSE' Or AREA_CL6 = 'Traffic Island' Or AREA_NA9 LIKE '%CITY WIDE OPEN SPACE%' Or AREA_NA9 LIKE '%PUBLIC ACCESS PROPERTY%' Or AREA_NA9 LIKE '%ZOO%' Or AREA_NA9 LIKE '%OLD FORT YORK%' Or AREA_NA9 LIKE '%EXHIBITION PLACE%' Or AREA_NA9 LIKE '%MUSEUM%' Or AREA_NA9 LIKE '%SCHOOL%' Or AREA_NA9 LIKE '%GOLF%' Or AREA_NA9 LIKE '%CEMETERY%' Or AREA_NA9 LIKE '%GRAVE%' Or AREA_NA9 LIKE '%MEDIAN%' Or AREA_NA9 LIKE '%TRAFFIC%' Or AREA_NA9 LIKE '%ROAD%' Or AREA_NA9 LIKE '%HIGHWAY%' Or AREA_NA9 LIKE '%EXPRESSWAY%' Or AREA_NA9 LIKE '%FREEWAY%' Or AREA_NA9 LIKE '%PARKING%' Or AREA_NA9 LIKE '%DRIVEWAY%' Or AREA_NA9 LIKE '%RAIL%' Or AREA_NA9 LIKE '%BUILDING%' Or AREA_NA9 LIKE '%STATION%' Or AREA_NA9 LIKE '%HOSPITAL%' Or AREA_NA9 LIKE '%INSTITUTION%' Or AREA_NA9 LIKE '%CAMPUS%' Or AREA_NA9 LIKE '%FACILITY%' Or AREA_NA9 LIKE '%OFFICE%' Or AREA_NA9 LIKE '%INDUSTRIAL%' Or AREA_NA9 LIKE '%LANDFILL%' Or AREA_NA9 LIKE '%TREATMENT%' Or AREA_NA9 LIKE '%RESTRICTED%' Or AREA_NA9 LIKE '%PROPOSED%' Or AREA_NA9 LIKE '%RESIDENTIAL%' Or AREA_NA9 LIKE '%GATED%' Or AREA_NA9 LIKE '%MEMBER%')


-- ---------------------------------------------------------------------
-- TIER 3: Other public and urban green space
-- ---------------------------------------------------------------------
(AREA_NA9 LIKE '%URBAN SPACE%' Or AREA_NA9 LIKE '%CITY WIDE OPEN SPACE%' Or AREA_NA9 LIKE '%GREEN SPACE%' Or AREA_NA9 LIKE '%CIVIC%' Or AREA_NA9 LIKE '%COMMONS%' Or AREA_NA9 LIKE '%SQUARE%' Or AREA_NA9 LIKE '%GARDEN%' Or AREA_NA9 LIKE '%LANDSCAPE%' Or AREA_NA9 LIKE '%COURTYARD%' Or AREA_NA9 LIKE '%HYDRO%' Or AREA_NA9 LIKE '%CORRIDOR%' Or AREA_NA9 LIKE '%GREENWAY%' Or AREA_NA9 LIKE '%LINEAR PARK%' Or AREA_NA9 LIKE '%LINEAR GREEN SPACE%' Or AREA_NA9 LIKE '%BOULEVARD%' Or AREA_NA9 LIKE '%COMMUNITY%')
AND NOT
(AREA_CL6 = 'Park' Or AREA_CL6 = 'Civic Centre Square' Or AREA_CL6 = 'Open Green Space' Or AREA_NA9 LIKE '%PARK%' Or AREA_NA9 LIKE '%PLAYGROUND%' Or AREA_NA9 LIKE '%ATHLETIC%' Or AREA_NA9 LIKE '%RECREATION%' Or AREA_NA9 LIKE '%SPORT%' Or AREA_NA9 LIKE '%CIVIC CENTRE%' Or AREA_NA9 LIKE '%CIVIC CENTER%')
AND NOT
(
  (AREA_NA9 LIKE '%RAVINE%' Or AREA_NA9 LIKE '%CREEK%' Or AREA_NA9 LIKE '%RIVER%' Or AREA_NA9 LIKE '%WATERCOURSE%' Or AREA_NA9 LIKE '%WOOD%' Or AREA_NA9 LIKE '%FOREST%' Or AREA_NA9 LIKE '%CONSERVATION%' Or AREA_NA9 LIKE '%NATURE%' Or AREA_NA9 LIKE '%NATURAL%' Or AREA_NA9 LIKE '%HERITAGE%' Or AREA_NA9 LIKE '%WETLAND%' Or AREA_NA9 LIKE '%MARSH%' Or AREA_NA9 LIKE '%MEADOW%' Or AREA_NA9 LIKE '%VALLEY%' Or AREA_NA9 LIKE '%ESCARPMENT%' Or AREA_NA9 LIKE '%BLUFF%' Or AREA_NA9 LIKE '%BEACH%' Or AREA_NA9 LIKE '%SYSTEM%' Or AREA_NA9 LIKE '%WATERSHED%' Or AREA_NA9 LIKE '%GREENBELT%' Or AREA_NA9 LIKE '%TRAIL%' Or AREA_NA9 LIKE '%WATERFRONT%' Or AREA_NA9 LIKE '%LAKEFRONT%' Or AREA_NA9 LIKE '%HARBOURFRONT%' Or AREA_NA9 LIKE '%BOARDWALK%' Or AREA_NA9 LIKE '%SHORELINE%' Or AREA_NA9 LIKE '%ISLAND%' Or AREA_NA9 LIKE '%HABITAT%' Or AREA_NA9 LIKE '%SANCTUARY%' Or AREA_NA9 LIKE '%ECOLOGICAL%' Or AREA_NA9 LIKE '%PRESERVE%' Or AREA_NA9 LIKE '%POND%' Or AREA_NA9 LIKE '%ARBORETUM%')
  AND NOT (AREA_NA9 LIKE '%HARWOOD HALL%' Or AREA_NA9 LIKE '%CRESTWOOD COLLEGE%' Or AREA_NA9 LIKE '%YORKWOODS LIBRARY%' Or AREA_NA9 LIKE '%NORTHWOOD COMMUNITY CENTRE%' Or AREA_NA9 LIKE '%CLIFFWOOD MANOR%' Or AREA_NA9 LIKE '%PIONEER%')
)
AND NOT
(AREA_CL6 = 'Cemetery' Or AREA_CL6 = 'Cul de Sac' Or AREA_CL6 = 'Golf Course' Or AREA_CL6 = 'OTHER_CEMETERY' Or AREA_CL6 = 'OTHER_GOLFCOURSE' Or AREA_CL6 = 'Traffic Island' Or AREA_NA9 LIKE '%CITY WIDE OPEN SPACE%' Or AREA_NA9 LIKE '%PUBLIC ACCESS PROPERTY%' Or AREA_NA9 LIKE '%ZOO%' Or AREA_NA9 LIKE '%OLD FORT YORK%' Or AREA_NA9 LIKE '%EXHIBITION PLACE%' Or AREA_NA9 LIKE '%MUSEUM%' Or AREA_NA9 LIKE '%SCHOOL%' Or AREA_NA9 LIKE '%GOLF%' Or AREA_NA9 LIKE '%CEMETERY%' Or AREA_NA9 LIKE '%GRAVE%' Or AREA_NA9 LIKE '%MEDIAN%' Or AREA_NA9 LIKE '%TRAFFIC%' Or AREA_NA9 LIKE '%ROAD%' Or AREA_NA9 LIKE '%HIGHWAY%' Or AREA_NA9 LIKE '%EXPRESSWAY%' Or AREA_NA9 LIKE '%FREEWAY%' Or AREA_NA9 LIKE '%PARKING%' Or AREA_NA9 LIKE '%DRIVEWAY%' Or AREA_NA9 LIKE '%RAIL%' Or AREA_NA9 LIKE '%BUILDING%' Or AREA_NA9 LIKE '%STATION%' Or AREA_NA9 LIKE '%HOSPITAL%' Or AREA_NA9 LIKE '%INSTITUTION%' Or AREA_NA9 LIKE '%CAMPUS%' Or AREA_NA9 LIKE '%FACILITY%' Or AREA_NA9 LIKE '%OFFICE%' Or AREA_NA9 LIKE '%INDUSTRIAL%' Or AREA_NA9 LIKE '%LANDFILL%' Or AREA_NA9 LIKE '%TREATMENT%' Or AREA_NA9 LIKE '%RESTRICTED%' Or AREA_NA9 LIKE '%PROPOSED%' Or AREA_NA9 LIKE '%RESIDENTIAL%' Or AREA_NA9 LIKE '%GATED%' Or AREA_NA9 LIKE '%MEMBER%')


-- ---------------------------------------------------------------------
-- EXCLUDED: Explicit exclusions OR anything matching no included tier
-- ---------------------------------------------------------------------
(AREA_CL6 = 'Cemetery' Or AREA_CL6 = 'Cul de Sac' Or AREA_CL6 = 'Golf Course' Or AREA_CL6 = 'OTHER_CEMETERY' Or AREA_CL6 = 'OTHER_GOLFCOURSE' Or AREA_CL6 = 'Traffic Island' Or AREA_NA9 LIKE '%CITY WIDE OPEN SPACE%' Or AREA_NA9 LIKE '%PUBLIC ACCESS PROPERTY%' Or AREA_NA9 LIKE '%ZOO%' Or AREA_NA9 LIKE '%OLD FORT YORK%' Or AREA_NA9 LIKE '%EXHIBITION PLACE%' Or AREA_NA9 LIKE '%MUSEUM%' Or AREA_NA9 LIKE '%SCHOOL%' Or AREA_NA9 LIKE '%GOLF%' Or AREA_NA9 LIKE '%CEMETERY%' Or AREA_NA9 LIKE '%GRAVE%' Or AREA_NA9 LIKE '%MEDIAN%' Or AREA_NA9 LIKE '%TRAFFIC%' Or AREA_NA9 LIKE '%ROAD%' Or AREA_NA9 LIKE '%HIGHWAY%' Or AREA_NA9 LIKE '%EXPRESSWAY%' Or AREA_NA9 LIKE '%FREEWAY%' Or AREA_NA9 LIKE '%PARKING%' Or AREA_NA9 LIKE '%DRIVEWAY%' Or AREA_NA9 LIKE '%RAIL%' Or AREA_NA9 LIKE '%BUILDING%' Or AREA_NA9 LIKE '%STATION%' Or AREA_NA9 LIKE '%HOSPITAL%' Or AREA_NA9 LIKE '%INSTITUTION%' Or AREA_NA9 LIKE '%CAMPUS%' Or AREA_NA9 LIKE '%FACILITY%' Or AREA_NA9 LIKE '%OFFICE%' Or AREA_NA9 LIKE '%INDUSTRIAL%' Or AREA_NA9 LIKE '%LANDFILL%' Or AREA_NA9 LIKE '%TREATMENT%' Or AREA_NA9 LIKE '%RESTRICTED%' Or AREA_NA9 LIKE '%PROPOSED%' Or AREA_NA9 LIKE '%RESIDENTIAL%' Or AREA_NA9 LIKE '%GATED%' Or AREA_NA9 LIKE '%MEMBER%')
OR
(
  NOT (AREA_CL6 = 'Park' Or AREA_CL6 = 'Civic Centre Square' Or AREA_CL6 = 'Open Green Space' Or AREA_NA9 LIKE '%PARK%' Or AREA_NA9 LIKE '%PLAYGROUND%' Or AREA_NA9 LIKE '%ATHLETIC%' Or AREA_NA9 LIKE '%RECREATION%' Or AREA_NA9 LIKE '%SPORT%' Or AREA_NA9 LIKE '%CIVIC CENTRE%' Or AREA_NA9 LIKE '%CIVIC CENTER%')
  AND NOT (
    (AREA_NA9 LIKE '%RAVINE%' Or AREA_NA9 LIKE '%CREEK%' Or AREA_NA9 LIKE '%RIVER%' Or AREA_NA9 LIKE '%WATERCOURSE%' Or AREA_NA9 LIKE '%WOOD%' Or AREA_NA9 LIKE '%FOREST%' Or AREA_NA9 LIKE '%CONSERVATION%' Or AREA_NA9 LIKE '%NATURE%' Or AREA_NA9 LIKE '%NATURAL%' Or AREA_NA9 LIKE '%HERITAGE%' Or AREA_NA9 LIKE '%WETLAND%' Or AREA_NA9 LIKE '%MARSH%' Or AREA_NA9 LIKE '%MEADOW%' Or AREA_NA9 LIKE '%VALLEY%' Or AREA_NA9 LIKE '%ESCARPMENT%' Or AREA_NA9 LIKE '%BLUFF%' Or AREA_NA9 LIKE '%BEACH%' Or AREA_NA9 LIKE '%SYSTEM%' Or AREA_NA9 LIKE '%WATERSHED%' Or AREA_NA9 LIKE '%GREENBELT%' Or AREA_NA9 LIKE '%TRAIL%' Or AREA_NA9 LIKE '%WATERFRONT%' Or AREA_NA9 LIKE '%LAKEFRONT%' Or AREA_NA9 LIKE '%HARBOURFRONT%' Or AREA_NA9 LIKE '%BOARDWALK%' Or AREA_NA9 LIKE '%SHORELINE%' Or AREA_NA9 LIKE '%ISLAND%' Or AREA_NA9 LIKE '%HABITAT%' Or AREA_NA9 LIKE '%SANCTUARY%' Or AREA_NA9 LIKE '%ECOLOGICAL%' Or AREA_NA9 LIKE '%PRESERVE%' Or AREA_NA9 LIKE '%POND%' Or AREA_NA9 LIKE '%ARBORETUM%')
    AND NOT (AREA_NA9 LIKE '%HARWOOD HALL%' Or AREA_NA9 LIKE '%CRESTWOOD COLLEGE%' Or AREA_NA9 LIKE '%YORKWOODS LIBRARY%' Or AREA_NA9 LIKE '%NORTHWOOD COMMUNITY CENTRE%' Or AREA_NA9 LIKE '%CLIFFWOOD MANOR%' Or AREA_NA9 LIKE '%PIONEER%')
  )
  AND NOT (AREA_NA9 LIKE '%URBAN SPACE%' Or AREA_NA9 LIKE '%CITY WIDE OPEN SPACE%' Or AREA_NA9 LIKE '%GREEN SPACE%' Or AREA_NA9 LIKE '%CIVIC%' Or AREA_NA9 LIKE '%COMMONS%' Or AREA_NA9 LIKE '%SQUARE%' Or AREA_NA9 LIKE '%GARDEN%' Or AREA_NA9 LIKE '%LANDSCAPE%' Or AREA_NA9 LIKE '%COURTYARD%' Or AREA_NA9 LIKE '%HYDRO%' Or AREA_NA9 LIKE '%CORRIDOR%' Or AREA_NA9 LIKE '%GREENWAY%' Or AREA_NA9 LIKE '%LINEAR PARK%' Or AREA_NA9 LIKE '%LINEAR GREEN SPACE%' Or AREA_NA9 LIKE '%BOULEVARD%' Or AREA_NA9 LIKE '%COMMUNITY%')
)
